

def handle_db_error(error):
    return 'Can\'t connect to main database', 500
